version: '3.8'
services:
  workly-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workly-frontend
    restart: always
    ports:
      - "3000:80" # Mapeia a porta 3000 do host para a porta 80 do contêiner Nginx
    environment:
      # Variáveis de ambiente para o build do Vite
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
      # Adicione outras variáveis VITE_... aqui se necessário
